// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7dQfop1ppPYRag7EOR-rC3_-bOj_9DiE',
    appId: '1:282440775443:web:12b9595745112429028ce6',
    messagingSenderId: '282440775443',
    projectId: 'arthico-3f433',
    authDomain: 'arthico-3f433.firebaseapp.com',
    storageBucket: 'arthico-3f433.firebasestorage.app',
    measurementId: 'G-GYPPNTYFZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrA70gxz5cpv-Hs65XYXQta22dVg4jIQ4',
    appId: '1:282440775443:android:6554571a2058a5f3028ce6',
    messagingSenderId: '282440775443',
    projectId: 'arthico-3f433',
    storageBucket: 'arthico-3f433.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFbTfv7liZfYYfzJ3Oe528JzyBbu1Z7f0',
    appId: '1:282440775443:ios:0fe9a23b06f62ec1028ce6',
    messagingSenderId: '282440775443',
    projectId: 'arthico-3f433',
    storageBucket: 'arthico-3f433.firebasestorage.app',
    iosBundleId: 'com.example.arthicoApp',
  );
}
